DUPLICATE_USER = 'HTTP Status 500 – Internal Server Error'
REGISTER_URI = 'https://petstore.octoperf.com/actions/Account.action'
DEFAULT_LANG = 'english'
DEFAULT_CATEGORY = 'BIRDS'
CONFIRMATION_TEXT = 'Thank you, your order has been submitted.'
